id: I6A7C064E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T11:21:38+00:00'
last_modified: '2022-06-08T10:42:59.234219+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD410
  title: ལམ་རིམ་མྱོང་ཁྲིད་ཟིན་བྲིས།（བོད་རྒྱ་སྐད་གཉིས་ཤན་སྦྱར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5F68:
      image_group_id: I4PD4548
      title: ''
      total_pages: 376
      order: 1
      base_file: 5F68.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
