id: P009396
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD410
  title: ལམ་རིམ་མྱོང་ཁྲིད་ཟིན་བྲིས།（བོད་རྒྱ་སྐད་གཉིས་ཤན་སྦྱར་མ།）
  author: ''
  volumes:
    c0b6d514d020491ca79c9d35e30d1a41:
      image_group_id: I4PD4548
      title: ''
      volume_number: 1
      total_pages: 376
      base_file: v001.txt
